import { ArrowLeft, ExternalLink, ShieldCheck } from "lucide-react";
import { Link } from "wouter";
import { ATTESTCOIN_INTEGRATION_STAGES, ATTESTCOIN_INTEGRATION_VERSION } from "@shared/attestcoin-integration";

const trustLayers = [
  ["Attestcoin Protocol", "Evidence authority", "The USC SDK proof path verifies source-chain history before it enters the credit file."],
  ["AI underwriter", "Advisory inference", "The model proposes calibrated risk signals and reason codes; it cannot sign or execute."],
  ["RiskGuard", "Deterministic policy", "Bounded amount, LTV, liquidity, freshness, and confidence checks remain authoritative."],
  ["Creditcoin", "Execution boundary", "Only explicit borrower acceptance can cross the constrained testnet execution path."],
] as const;

export default function Docs() {
  return <main className="min-h-screen bg-[#070b12] px-4 py-6 text-slate-100 sm:px-6 sm:py-10">
    <div className="mx-auto max-w-6xl">
      <header className="flex flex-wrap items-center justify-between gap-4 border-b border-white/10 pb-6">
        <div className="flex items-center gap-3"><div className="grid h-10 w-10 place-items-center rounded-2xl border border-cyan-300/20 bg-cyan-300/10 text-cyan-300"><ShieldCheck size={20} /></div><div><div className="font-semibold tracking-tight">ProofLoan</div><div className="text-[10px] uppercase tracking-[.2em] text-slate-500">Integration documentation</div></div></div>
        <Link href="/" className="inline-flex items-center gap-2 rounded-full border border-white/10 px-3 py-2 text-xs font-semibold text-slate-300 transition hover:border-cyan-300/40 hover:text-cyan-200"><ArrowLeft size={14} /> Back to borrower flow</Link>
      </header>
      <section className="py-12 sm:py-16"><div className="max-w-3xl"><p className="text-xs font-bold uppercase tracking-[.24em] text-cyan-300">Attestcoin Protocol × Creditcoin</p><h1 className="mt-4 text-4xl font-black tracking-[-.04em] text-white sm:text-6xl">Proof before underwriting.</h1><p className="mt-6 text-base leading-7 text-slate-400 sm:text-lg sm:leading-8">ProofLoan uses the Attestcoin Protocol as a verifiable evidence boundary. A live request begins with a mined source transaction, waits for attestation, builds a proof through the USC SDK, and verifies that proof at the Creditcoin boundary. Only a successful verification becomes typed evidence for the underwriting pipeline.</p><div className="mt-6 flex flex-wrap gap-2 text-[10px] uppercase tracking-[.14em]"><span className="rounded-full border border-cyan-300/25 bg-cyan-300/10 px-3 py-2 text-cyan-200">{ATTESTCOIN_INTEGRATION_VERSION}</span><span className="rounded-full border border-amber-300/25 bg-amber-300/10 px-3 py-2 text-amber-200">Live path fails closed</span><span className="rounded-full border border-purple-300/25 bg-purple-300/10 px-3 py-2 text-purple-200">Preview is labeled</span></div></div></section>
      <section aria-label="Attestcoin lifecycle" className="grid gap-3 md:grid-cols-5">{ATTESTCOIN_INTEGRATION_STAGES.map((stage, index) => <article key={stage.stage} className="rounded-2xl border border-white/10 bg-[#0d1622] p-4"><div className="flex items-center justify-between gap-2"><span className="text-xs font-bold text-cyan-300">0{index + 1}</span><span className="text-[9px] uppercase tracking-[.12em] text-slate-600">{stage.stage.replaceAll("_", " ")}</span></div><h2 className="mt-5 text-sm font-bold text-white">{stage.label}</h2><p className="mt-2 text-xs leading-5 text-slate-400">{stage.action}</p><div className="mt-4 border-t border-white/10 pt-3"><p className="text-[10px] font-semibold uppercase tracking-[.12em] text-cyan-200">Authority · {stage.authority}</p><p className="mt-2 text-[11px] leading-5 text-amber-200/75"><span className="font-semibold text-amber-200">Fail closed:</span> {stage.failClosed}</p></div></article>)}</section>
      <section className="mt-12 grid gap-4 md:grid-cols-2"><div className="rounded-3xl border border-white/10 bg-[#0b121d] p-5 sm:p-7"><p className="text-xs font-bold uppercase tracking-[.2em] text-cyan-300">Trust boundary</p><h2 className="mt-3 text-2xl font-black text-white">Each layer has one job.</h2><div className="mt-6 space-y-3">{trustLayers.map(([name, role, body]) => <div key={name} className="rounded-2xl border border-white/10 bg-white/[.03] p-4"><div className="flex flex-wrap items-center justify-between gap-2"><span className="font-semibold text-white">{name}</span><span className="text-[10px] uppercase tracking-[.12em] text-cyan-200">{role}</span></div><p className="mt-2 text-sm leading-6 text-slate-400">{body}</p></div>)}</div></div><div className="rounded-3xl border border-white/10 bg-[#0b121d] p-5 sm:p-7"><p className="text-xs font-bold uppercase tracking-[.2em] text-purple-300">Implementation map</p><h2 className="mt-3 text-2xl font-black text-white">What the live path produces.</h2><div className="mt-6 space-y-4 text-sm leading-6 text-slate-400"><p><span className="font-semibold text-emerald-300">VerifiedFact:</span> source chain, source block, transaction hash, event type, amount, verification block, freshness, proof root, and explicit live mode.</p><p><span className="font-semibold text-purple-300">FeatureVector:</span> deterministic aggregates are constructed only after evidence-root validation and chronology checks.</p><p><span className="font-semibold text-amber-300">Decision:</span> AI output is sanitized, bounded, fingerprinted, and passed through deterministic RiskGuard policy.</p><p><span className="font-semibold text-cyan-300">Execution:</span> acceptance uses replay protection and remains auditable even when a durable finalization step fails.</p></div><a href="https://docs.creditcoin.org/attestcoin-protocol/dapp-builder-infrastructure/attestcoin-sdk-usc-sdk.md" target="_blank" rel="noreferrer" className="mt-7 inline-flex items-center gap-2 text-sm font-semibold text-cyan-300 hover:text-cyan-200">Open USC SDK documentation <ExternalLink size={15} /></a></div></section>
      <footer className="mt-12 border-t border-white/10 pt-6 text-xs text-slate-600">ProofLoan · Attestcoin Protocol integration summary · Creditcoin testnet demo</footer>
    </div>
  </main>;
}
